language: go
go:
    - 1.5
sudo: false
install:
    - go get -u github.com/gopherjs/gopherjs
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    - npm install -g jasmine

before_script:
    - gopherjs build ./spec/jasmine-spec.go -o ./spec/jasmine-spec.js

script:
    - jasmine
